// Character descriptions database
window.characterDescriptions = {
 // Section 1: Character Type/Base Body descriptions
    "Standard Male Warrior": "Sculpted to perfection with battle-hardened muscles and a thousand-yard stare that's seen it all! This peak-human warrior stands ready for action!",
    "Standard Female Warrior": "Fierce and fearless with aerodynamic curves designed for maximum combat efficiency! This warrior goddess means business!",
    "Muscular Barbarian": "MASSIVE MIGHT! Rippling with primal power, this savage warrior packs the punch of ten men in one hulking frame!",
    "Athletic Ninja": "Sleek as shadow, swift as wind! This lean fighting machine moves with deadly grace and strikes like lightning!",
    "Stocky Wrestler Build": "Built like a human tank! This powerhouse champion crushes enemies with overwhelming force and unbreakable will!",
    "Tall Lanky Spy": "Towering above the rest, this master of infiltration slips through security like smoke through fingers!",
    "Cybernetically Enhanced Human": "Part man, part machine, ALL AWESOME! Circuitry pulses beneath reinforced skin as technology meets raw human power!",
    "Mutated Human": "Transformed by unknown forces! Crackling energy surges through veins as this evolution of mankind discovers newfound power!",
    "Battle-Scarred Veteran": "Every scar tells a story of victory! This grizzled warrior bears the marks of countless battles survived!",
    "Clone Trooper Variant": "Born from the ultimate blueprint for battle! Mass-produced for mayhem, this soldier shows slight variations from his brothers!",
    "Insectoid": "From deep space comes this six-armed terror! Compound eyes scan for prey while chitinous armor deflects all attacks!",
    "Reptilian Humanoid": "Cold-blooded killer from the stars! Scales shimmer with alien power as forked tongue tastes fear in the air!",
    "Amphibious Fish-man": "From ocean's darkest depths emerges this gill-breathing terror! Webbed claws drip with seawater doom!",
    "Crystalline Being": "Formed from living crystal, this prismatic warrior refracts light into deadly laser arrays! UNBREAKABLE!",
    "Slime-based Creature": "Oozing unstoppable menace! This amorphous horror flows through any gap, consuming all in its gelatinous path!",
    "Skeletal Undead": "Death has no dominion over this bone-rattling warrior! Risen from beyond to exact eternal vengeance!",
    "Energy Elemental": "PURE PLASMA POWER! This living lightning bolt crackles with barely-contained cosmic energy!",
    "Tentacled Aberration": "Squirming, writhing, UNSTOPPABLE! Multiple tentacles lash out with alien intelligence and endless hunger!",
    "Lava Rock Monster": "Born from volcanic fury! This molten monstrosity leaves trails of fire wherever it stomps!",
    "Ice Creature": "Frozen fury given form! Sub-zero death stalks on crystalline legs, leaving frost in its wake!",
    "Sleek Android": "Streamlined for efficiency! This metallic marvel combines cutting-edge design with devastating firepower!",
    "Boxy Military Robot": "Tank-tough and battlefield-ready! This walking weapons platform bristles with angular armor and heavy artillery!",
    "Transformable Mech Body": "TWO TOYS IN ONE! Transform from humanoid warrior to devastating war machine with snap-lock action!",
    "Cyborg": "Where flesh meets steel! Half-human determination powers half-machine perfection in this ultimate warrior upgrade!",
    "Tank-based Robot": "Rolling thunder! This treaded terror combines tank treads with humanoid weapons systems for maximum destruction!",
    "Spider/Multi-leg Robot": "Eight-legged engine of destruction! This arachnid automaton scuttles across any surface with mechanical menace!",
    "Combat Droid": "Programmed for pure combat efficiency! This battle-bot calculates victory with cold mechanical precision!",
    "Stealth Infiltrator Unit": "Silent but deadly! This ninja-robot slips past security systems to deliver high-tech destruction!",
    "Power-armored Soldier": "Man and machine in perfect harmony! Pilot and power suit merge to create the ultimate warrior!",
    "Bio-mechanical Hybrid": "DNA meets circuitry! This grotesque fusion of organic tissue and cold steel defies nature itself!",
    "Ninja Turtle": "Cowabunga-ready hero in a half-shell! This radical reptile combines teenage attitude with ancient ninja skills!",
    "Mutant Monkey/Ape": "Gone ape with power! This primate powerhouse swings into action with super-simian strength!",
    "Armored Bear": "Grizzly might behind armored might! This ursine warrior packs the punch of a freight train!",
    "Cyber-Wolf": "Howling with chrome hunger! This cyber-enhanced canine hunts with technological precision and feral fury!",
    "Battle Cat": "Feline ferocity meets combat readiness! This armored predator prowls for justice with razor-sharp claws!",
    "Martial Arts Duck": "Quack-FU action! This feathered fighter waddles into battle with deadly beak and web-footed kicks!",
    "Rhino Warrior": "Charging forward with one ton of armored muscle! This horned horror crushes opposition flat!",
    "Shark Soldier": "Land shark on the prowl! Rows of razor teeth and military hardware create the perfect predator!",
    "Hawk Person": "Soaring on wings of justice! This avian avenger swoops down to snatch victory from the talons of defeat!",
    "Martial Arts Rabbit": "Hop to the attack! This cotton-tailed warrior delivers lightning-fast kicks that'll bowl you over!",
    "Robot/Animal": "Nature meets technology in this terrifying fusion! Mechanical precision combines with animal instinct!",
    "Human/Alien": "Merged genetics create the ultimate warrior! Human heart powers alien abilities in this cosmic champion!",
    "Human/Robot": "Enhanced beyond human limits! Cybernetic systems boost human potential to superhuman levels!",
    "Alien/Animal": "From distant worlds comes this beast! Unknown science created this perfect predator from another galaxy!",
    "Monster/Machine": "Unholy alliance of horror and technology! Pistons pump greenish ichor through mechanical muscles!",
    "Spirit/Human": "Possessed by ancient power! This ghostly warrior phases between worlds with supernatural strength!",
    "Plant/Human": "Photosynthetic powerhouse! Vines and thorns erupt from flesh as chlorophyll fuels incredible abilities!",
    "Insect/Robot": "Buzz into battle! Mechanical mandibles and chrome exoskeleton create the perfect pest-control unit!",
    "Fish/Space Alien": "Swimming through space itself! This cosmic sea-thing navigates stellar currents with tentacle-tipped fins!",
    "Dragon/Human": "Breathing fire with human fury! Scales shimmer beneath armor as dragon-blood burns within!",
    
    // Section 2: Body Build/Scale descriptions
    "Regular Joe": "Everyman hero with real-world proportions! This battle-ready warrior proves that heart beats size every time!",
    "Sleek Assassin": "Deadly efficient design with no wasted motion! This lean machine cuts through missions like a hot knife through butter!",
    "Field Scout": "Perfectly proportioned for recon duty! This battlefield observer stays light on his feet for maximum mobility!",
    "Tech Support": "Standard frame packed with brains over brawn! This support specialist proves that knowledge is the ultimate weapon!",
    "Medical Officer": "Human-scale hero with healing touch! This combat medic combines compassion with battlefield courage!",
    "Communications Operator": "Baseline build for long-term operations! This signal specialist connects teams across continents!",
    "Standard Android": "Factory specifications meet battlefield needs! This medium-frame machine balances power with precision!",
    "Regular Mutant": "Mutated from human normal into something more! Basic frame masks incredible hidden potential!",
    "Average Alien Warrior": "Standard-issue for its species, extraordinary by Earth standards! This cosmic soldier brings alien edge to any battle!",
    "Common Grunt": "Core combat frame for the rank and file! This trooper represents millions ready for action!",
    "Elite Commando": "Chiseled for combat! Every sculpted muscle tells the story of a thousand missions survived!",
    "Special Forces Warrior": "Lean, mean fighting machine! This battle-hardened body carries the strength of elite training!",
    "Navy SEAL Build": "Underwater excellence sculpted in flesh! This aquatic warrior cuts through waves and enemies alike!",
    "Ranger": "Mountain-moving muscle with marathon endurance! This ranger runs missions at peak performance!",
    "Team Leader Physique": "Commanding presence with carved confidence! This heroic frame inspires troops to follow into hell!",
    "Sniper Build": "Perfectly proportioned for precision! This sharpshooter's controlled physique never compromises a shot!",
    "Paratrooper Body": "Jump-ready with reinforced muscle! This airborne athlete drops from the sky with deadly grace!",
    "Martial Artist": "Tournament-toned for tournament terror! This fighting frame flows like water, strikes like stone!",
    "Precision Operative": "Balanced build for specialized missions! Every muscle calculated for maximum efficiency!",
    "Espionage Agent": "Athletic aesthetic hiding deadly potential! This spy's body looks civilian but thinks combat!",
    "Bodybuilder Behemoth": "MOUNTAIN OF MUSCLE! This Herculean hero measures strength in tons and fear in screams!",
    "Barbarian Warrior": "SAVAGE BULK ACTIVATED! This primitive powerhouse crushes steel with bare hands!",
    "Power Lifter": "COMPETITION-CRUSHING MASS! This weight-class warrior bench-presses battle tanks!",
    "Viking Berserker": "NORDIC THUNDER INCARNATE! Bulging with battle-rage and capable of splitting logs with biceps!",
    "Strong Man Champion": "CARNIVAL OF CARNAGE! This thick-set titan juggles cannonballs and snaps chains for fun!",
    "Tank Commander": "ARMOR-PLATED ANATOMY! This heavy-duty handler manhandles artillery with ease!",
    "Mountain Man": "WILDERNESS BULK UNLEASHED! This frontier fortress combines grizzly strength with mountain man might!",
    "Wrestling Champion": "SQUARED CIRCLE SUPER-SIZE! This grappling giant slams opponents into submission!",
    "Heavy Artillery": "WALKING WEAPON SYSTEM! This mobile muscle mountain carries firepower equal to his physique!",
    "Combat Monster": "MAXIMUM MASS, MINIMUM MERCY! This battle-beast breaks tanks like breadsticks!",
    "Shadow Ninja": "Impossibly thin for impossible missions! This wraith-like warrior slips through security like smoke!",
    "Stealth Operative": "Paper-slim profile for perfect infiltration! This ghost glides where others cannot go!",
    "Acrobat": "Cirque-trained and combat-ready! This flexible fighter flips death at every turn!",
    "Spider Build": "Web-swinging slender! This arachnid athlete clings to walls with wall-crawler ease!",
    "Thief": "Slinky and sinister! This larcenous leopard prowls for prizes unseen and unheard!",
    "Jungle Scout": "Vine-swinging slim! This canopy crawler moves through foliage like wind through leaves!",
    "Urban Runner": "Parkour perfection! This city-sprinting speedster turns concrete into playground!",
    "Underground Explorer": "Cave-crawling compact! This subterranean specialist squeezes through cracks others can't see!",
    "Quick Strike Assassin": "Razor-sharp and rapier-fast! This lightning-lean killer strikes before shadows fall!",
    "Infiltrator": "Ultra-slim espionage excellence! This impossibly thin spy bends through laser grids!",
    "Blob Monster": "AMORPHOUS HORROR UNLEASHED! This shapeshifting nightmare flows through gaps like living sludge!",
    "Hunchback Mutant": "TWISTED BY SCIENCE GONE WRONG! One massive shoulder bulges with unbridled power!",
    "Tumor-ridden Beast": "MEDICAL NIGHTMARE MANIFESTED! Grotesque growths pulse with alien energy across its frame!",
    "Swollen Experiment": "LAB ACCIDENT CATASTROPHE! Bloated beyond recognition, this failed creation seeks revenge!",
    "Asymmetric Brute": "EVOLUTIONARY ODDITY! One side rippling with muscle, the other sleek with speed!",
    "Mutated Powerhouse": "RANDOM MUSCLE EXPLOSION! Bulk appears in unexpected places on this genetic jumble!",
    "Toxic Waste Victim": "CHEMICAL CATASTROPHE INCARNATE! Bloated with radioactive runoff, this eco-monster oozes doom!",
    "Failed Experiment": "FRANKENSTEIN'S FURY! Mismatched parts create a patchwork predator that defies nature!",
    "Radiation Mutant": "NUCLEAR NIGHTMARE! Gamma-grown mass shifts and warps with each radioactive pulse!",
    "Living Nightmare": "SANITY-SHATTERING SHAPE! This impossible anatomy exists to haunt your dreams!",

    // Section 3: Head/Face Type descriptions
    "Square-jawed Hero": "CHISELED PERFECTION! This granite-solid jawline cuts through evil with determination etched in every feature!",
    "Chiseled Commando": "BATTLE-HARDENED HANDSOMENESS! Combat scars add character to this warrior's movie-star face!",
    "Battle-Scarred Face": "WAR-TORN VISAGE OF VICTORY! Each mark tells the tale of missions impossible made possible!",
    "Youthful Rookie": "FRESH-FACED FIGHTER! This baby-faced warrior masks deadly skill behind boyish charm!",
    "Grizzled Veteran": "SEEN-IT-ALL SOLDIER! A weathered face that's launched a thousand missions and lived to tell!",
    "Pretty Boy Operative": "UNDERCOVER DREAMBOAT! This handsome hero's good looks hide deadly expertise!",
    "Tough-guy Mercenary": "STONE-COLD STARE OF STEEL! This hard-faced hitman's glare alone can stop enemies cold!",
    "Distinguished Commander": "LEADERSHIP ETCHED IN FEATURES! Silver-streaked wisdom commands respect and inspires courage!",
    "Rugged Explorer": "WILDERNESS-WEATHERED WANDERER! Sun-baked skin tells tales of global adventure!",
    "Clean-cut Soldier": "ALL-AMERICAN ASSAULT! This regulation-perfect face represents freedom itself!",
    "Classic Skull Face": "DEATH'S HEAD DESIGN! This bone-bare visage strikes fear into the very marrow of enemies!",
    "Burning Skull": "FLAMING PHANTOM FACE! Hellfire blazes from eye sockets as this soul scorches scorched earth!",
    "Cybernetic Skull": "TECH-TERROR CRANIUM! Half-chrome death's head processes targeting data with undead efficiency!",
    "Exposed Brain Skull": "MAD SCIENTIST'S MASTERPIECE! Pulsing gray matter powers this thinking terror machine!",
    "Alien Skull Variant": "EXTRATERRESTRIAL EXOSKELETON! This space-age skeleton proves death knows no planetary boundaries!",
    "Armored Skull": "BATTLE-PLATED BONE! This reinforced cranium laughs off explosions while dealing doom!",
    "Crystalline Skull": "DIAMOND-DEATH DESIGN! Faceted bone-structure refracts fear into prismatic terror!",
    "Robot Skull Head": "MECHANICAL MORTALITY! This servo-powered skull calculates casualties with cold precision!",
    "Demonic Skull": "HELLSPAWN HORROR HEAD! Horned bone-face channels infernal power through smoking sockets!",
    "Space Pirate Skull": "COSMIC CORSAIR CRANIUM! This star-faring skeleton sails solar winds in search of plunder!",
    "Insect Compound Eyes": "MULTI-VISION MENACE! Hundreds of hexagonal eyes track every movement in perfect detail!",
    "Reptilian Snake Head": "SERPENT SUPREME! This cold-blooded cranium hypnotizes prey before the strike!",
    "Tentacle Face": "CTHULHU COUNTENANCE! Writhing appendages replace features on this sanity-shredding visage!",
    "Multi-eyed Horror": "OMNISCIENT OBSERVER! This many-eyed monster sees all, judges all, devours all!",
    "Crystal Shard Face": "PRISM PREDATOR PROFILE! Faceted features refract reality into geometric terror!",
    "Energy Being Head": "PURE PLASMA PORTRAIT! This swirling vortex of power has no fixed features!",
    "Aquatic Gill Face": "DEEP SEA DEMENTOR! Breathing apparatus built into flesh filters air and spreads fear!",
    "Beak-headed Warrior": "AVIAN ASSAULT VISAGE! This predatory profile pecks prey with precision!",
    "Mollusk Head": "CEPHALOPOD CHAMPION! Sucker-covered skin shifts color with mood and mission!",
    "Elephant-like Alien": "COSMIC PACHYDERM PROFILE! This trunk-wielding terror trumpets doom across galaxies!",
    "Classic R2-D2 Dome": "RETRO-ROBOT ROUNDNESS! This dome-headed droid beeps binary battle plans!",
    "Boxy Computer Head": "MAINFRAME COUNTENANCE! Angular armor houses processing power beyond comprehension!",
    "Sleek Android Face": "STREAMLINED SERVO-SKULL! Aerodynamic design cuts through air resistance and opposition!",
    "Multi-sensor Head": "360-DEGREE DETECTOR! This sensor-studded sphere scans for threats in all directions!",
    "Battle Damage Robot": "WAR-WORN WARRIOR-BOT! Blast craters and bullet holes prove this machine means business!",
    "Scanner Eye Unit": "CYCLOPS COMPUTER CRANIUM! This single red eye pierces through lies and laser shields!",
    "Communication Array Head": "ANTENNA ASSAULT APPARATUS! This signal-sending skull coordinates chaos from afar!",
    "Weapon Platform Head": "ARTILLERY AUTOMATION! This mobile turret thinks weapons, breathes bullets!",
    "Radar Dish Head": "DETECTION DOME OF DOOM! This spinning sensor sweeps for signatures of destruction!",
    "Modular CPU Unit": "PLUG-AND-PLAY PROCESSOR! This customizable cranium adapts to any combat situation!",
    "Wolf Snout": "LUPINE LEADER PROFILE! This pack-alpha profile howls orders while hunting for justice!",
    "Bear Face": "GRIZZLY GRIMACE OF GLORY! This ursine visage combines cuddly and crushing power!",
    "Cat Warrior": "FELINE FIGHTER FACE! Whiskers twitch with predatory precision as pupils narrow to kill!",
    "Crocodile Jaws": "REPTILE RAGE READY! These crushing jaws snap steel like spaghetti!",
    "Shark Mouth": "OCEANIC OBLITERATION! Rows of razor teeth promise permanent problem-solving!",
    "Raptor Beak": "PREHISTORIC PREDATOR PROFILE! This hooked horror hooks heroes and villains alike!",
    "Gorilla Face": "PRIMATE POWER PERSONIFIED! Intelligent eyes peer from beneath beastly brow!",
    "Serpent Head": "VENOM-VOICED VILLAIN! Forked tongue tastes fear while fangs deliver final justice!",
    "Bulldog Muzzle": "TENACIOUS TERRIER VISAGE! This jowl-jiggling warrior never lets go, never gives up!",
    "Tiger Striped": "STRIPED STALKER SUPREME! This big-cat countenance prowls for prey day and night!",
    "Ninja Face Wrap": "SHADOW WARRIOR SHROUD! This mysterious mask muffles identity while maintaining menace!",
    "Combat Goggles Mask": "BUG-EYED BATTLE BUDDY! These oversized optics optimize operations in any environment!",
    "Wrestling Style Mask": "LUCHADOR LEGEND LOOK! This colorful covering conceals identity while revealing awesome!",
    "Plague Doctor Mask": "MEDIEVAL MENACE MODERNIZED! That beak-like barrier blocks disease and distributes fear!",
    "Samurai Face Guard": "HONOR-BOUND HIDING! This traditional covering protects identity while preserving bushido!",
    "Hockey-style Mask": "SLASHER SPECIAL SHIELDING! This puck-proof protection promises punishment!",
    "Biker Full Face": "ROAD RAGE BARRIER! This leather-and-chrome cover channels rebellion!",
    "Commando Balaclava": "SPECIAL OPS SECRECY! This mission-ready mask maintains mystery!",
    "Arabian Face Veil": "DESERT MYSTERY MASKING! This flowing fabric filters sand and secrets!",
    "Tribal War Mask": "PRIMITIVE POWER PAINT! These ritual markings transform warrior into weapon!",
    "Space Helmet": "COSMIC CONTAINMENT UNIT! This clear-dome cranium protection preserves life in the void!",
    "Combat Infantry Helmet": "BATTLE-TESTED BRAIN BUCKET! This dented dome has deflected doom a thousand times!",
    "Pilot's Flight Helmet": "TOP GUN TOPPER! This high-tech headgear houses communication and cool factor!",
    "Deep Sea Diving Bell": "PRESSURE-PROOF PROTECTION! This bulbous barrier battles both water and warriors!",
    "Radiation Suit Helmet": "NUCLEAR NIGHTMARE NEGATOR! This lead-lined lid laughs at lethal radiation!",
    "Motorcycle Racing Helm": "SPEED DEMON SKULL SHIELD! This aerodynamic armor cuts through wind and enemies!",
    "Alien Containment Hood": "ATMOSPHERIC ADAPTER! This life-support lid lets aliens breathe in Earth's air!",
    "Tactical Assault Helmet": "COMBAT COMMAND CENTER! This hi-tech helmet houses targeting computers and terror!",
    "Astronaut EVA Suit": "SPACEWALK SURVIVAL SPHERE! This exploration enclosure enables extra-vehicular excellence!",
    "Tank Commander Helm": "ARMORED ASSAULT AUTHORITY! This commander's cap contains communication and courage!",

    // Section 4: Accessories/Gear descriptions
    "Laser Rifle": "ZAP-ACTION ACCURACY! This photonic firearm fires beams of pure destruction!",
    "Energy Sword": "PLASMA BLADE OF DESTINY! This crackling saber slices through metal and myth!",
    "Plasma Cannon": "SUPERHEATED SUPERIORITY! This molten-metal magnifier melts opposition!",
    "Missile Launcher": "ROCKET-POWERED RETRIBUTION! Lock and launch destruction with pinpoint precision!",
    "Assault Blaster": "RAPID-FIRE RAGE! This trigger-happy terror spits hot death at 2000 rounds per minute!",
    "Flame Thrower": "INFERNO INDUCER! Paint the town red with this portable pyroclastic party-starter!",
    "Ice Ray Gun": "FREEZE-FRAME FURY! This cryogenic cannon crystallizes criminals instantly!",
    "Electric Staff": "THUNDERSTICK OF JUSTICE! Channel lightning through this voltage vara!",
    "Sci-fi Battle Axe": "PLASMA-POWERED CHOPPER! This energy edge cuts through armor and arguments!",
    "Bio Weapons": "ORGANIC OBLITERATION! These living weapons pulse with predatory purpose!",
    "Force Field Generator": "INVISIBLE INVINCIBILITY! This pocket-sized projector creates impenetrable plasma barriers!",
    "Riot Shield": "CROWD-CONTROL CLASSIC! This reinforced blocker bounces bullets and protesters alike!",
    "Energy Barrier Disk": "ROTATING RESISTANCE! This spinning shield sends projectiles packing with style!",
    "Roman-style Shield": "GLADIATOR GUARDIAN! This ancient armor adapter blocks modern mayhem!",
    "Turtle Shell Defense": "BATTLE SHELL BUFFER! This back-mounted barrier blocks while allowing mobility!",
    "Magnetic Deflector": "METAL-REPELLING MARVEL! This magnetic marvel sends steel back to sender!",
    "Laser Blocking Shield": "PHOTON-PROOF PROTECTION! This reflective barrier bounces light-speed doom!",
    "Retractable Arm Guard": "FLIP-OUT FORTRESS! This forearm defender deploys at light speed!",
    "Rotating Defense System": "SPINNING SECURITY! This whirling wall of defense deflects from all angles!",
    "Bubble Shield": "SPHERE OF SAFETY! This transparent barrier blocks blast while showing the action!",
    "Jetpack": "ROCKET-POWERED FREEDOM! Blast off to victory with twin-turbo thrust technology!",
    "Oxygen Tank System": "BREATHE EASY ANYWHERE! This life-support system cycles air in any atmosphere!",
    "Weapon Storage Pack": "ARSENAL ON AUTOPILOT! This modular magazine holds more firepower than physics allows!",
    "Communications Array": "COMMAND CENTER CARRY! This mobile communication base connects commanders to chaos!",
    "Power Core Backpack": "ENERGY ENDLESS! This fusion battery pack powers weapons indefinitely!",
    "Spy Gadget Pack": "SECRET AGENT ARSENAL! Hidden compartments hold high-tech trickery!",
    "Medical Supply Unit": "COMBAT MEDIC MAGIC! This healing station houses hi-tech health packs!",
    "Energy Battery Pack": "JUICE UP FOR JUSTICE! This plasma power source supercharges any system!",
    "Stealth Generator": "CLOAK AND CARRY! This invisibility inducer includes built-in battery pack!",
    "Portable Computer": "BATTLEFIELD BRAIN BOX! This mobile mainframe calculates victory scenarios!",
    "Grappling Hook Gun": "CLIMB IT QUICK! This wall-scaling wonder launches heroes to new heights!",
    "Multi-function Scanner": "SCAN FOR SECURITY! This all-purpose analyzer detects danger and opportunity!",
    "Repair Kit Module": "BATTLEFIELD FIXER! This emergency engineer saves missions with modular magic!",
    "Hacking Device": "CODE-CRACK CHAMPION! This digital skeleton key opens any electronic lock!",
    "Cutting Torch": "BURNTHROUGH BUDDY! This plasma cutter melts metal like butter!",
    "Lock Pick Set": "SILENT ENTRY SPECIALIST! These precision picks open anything quietly!",
    "Secret Camera": "COVERT CAM! This hidden eye records evidence while looking innocent!",
    "Tracking Beacon": "KEEP-TABS TECH! This tiny transmitter trails targets anywhere!",
    "Magnetic Boots": "STICK ANYWHERE! These powered pumps walk walls and ceilings!",
    "Universal Translator": "BABEL BUSTER! This language processor speaks every tongue!",
    "Rocket Booster Attachment": "SPEED BOOST BEAUTY! This add-on engine amplifies acceleration amazingly!",
    "Tank Tread Add-on": "TRACTION TRANSFORMATION! Convert any ride into rolling rumble!",
    "Helicopter Rotor Pack": "WHIRLY UPGRADE! Turn figure into flying force with spinning blades!",
    "Submarine Propeller": "UNDERWATER ACCELERATOR! This aquatic attachment enables submarine speed!",
    "Hover Disc Platform": "ANTI-GRAVITY AWESOME! Float above the fray with this levitation station!",
    "Rail Gun Module": "MAGNETIC ACCELERATION! This electromagnetic enhancer amplifies artillery!",
    "Energy Shield Pod": "MOBILE PROTECTION! This defensive dome deploys from any vehicle!",
    "Armor Plating": "ADD-ON ARMOR! This reinforcement resists damage from every direction!",
    "Vehicle Control Panel": "COMMAND CENTER COMPONENT! This cockpit conversion pilots any craft!",
    "Detachable Wheels": "ROLL OR WALK! These modular wheels wheel away for walking action!",

    // Section 5: Action Features descriptions
    "Spinning Backhand Punch": "WHIRLING WALLOP! Wind-up this warrior's waist for spinning strike action!",
    "Power Kick Action": "SNAP-KICK SPECTACULAR! Press the leg for lightning-fast kicking combat!",
    "Missile-firing Chest": "CHEST CANNON CHAOS! Load tiny rockets and fire from surprising places!",
    "Spring-launch Punch": "PUNCH POWER ACTIVATED! Pull back the arm for knock-out boxing action!",
    "Head-butt Attack": "SKULL-CRUSHING SPECIAL! Push the head down for devastating battle bonk!",
    "Waist-twist Chop": "TORNADO CHOP! Twist the torso for karate-chopping combat moves!",
    "Knee-strike Action": "LEG LAMP UP! Wind and release for bone-breaking knee smash!",
    "Quick-draw Weapon": "FASTEST GUN FURY! Trigger this feature for lightning-fast weapon draw!",
    "Grab & Slam Motion": "WRESTLING WONDER! Press for powerful grappling action moves!",
    "Tail Whip Action": "REPTILE RUMBLE! Flick the switch for devastating tail-sweep attack!",
    "Glowing Chest Symbol": "POWER CORE PULSE! This heroic heart glows with righteous energy!",
    "LED Eye Beams": "LASER VISION ACTIVATED! Press button for targeting light show!",
    "Illuminated Weapon": "GLOWING GUN GLORY! This lit-up launcher lights up the night!",
    "Power Core Glow": "ENERGY EXPOSED! This pulsing power source shows inner strength!",
    "Laser Sights": "BULLSEYE BEAM! These targeting lights guarantee perfect aim!",
    "Warning Lights": "DANGER DISPLAY! Flashing alarms announce incoming attack!",
    "Hologram Projector": "PIXEL PROJECTION! This mini-light creates convincing copies!",
    "Jetpack Thrusters": "FLAME-OUT FANTASTIC! Watch realistic rocket fire illuminate!",
    "Energy Field Pulse": "FORCE FIELD FLASH! This defensive dome glows with protective power!",
    "Tracking Beacon": "BLINK AND YOU'LL FIND IT! This locator light leads the way!",
    "Acid Spit Attack": "TOXIC SPRAY! Fill with water for alien acid-spit action!",
    "Water Gun Blast": "SOAKER SURPRISE! This liquid launcher loads up for wet warfare!",
    "Poison Spray": "VENOM VOLLEY! Fill reservoir for venomous villain action!",
    "Flame Liquid Stream": "FIRE-WATER FURY! Squirt orange liquid for flame-thrower effects!",
    "Slime Shot": "GOO GOES FLYING! This slime-slinger splatters green gunk!",
    "Oil Slick Spray": "SLIPPERY SITUATION! Create skating surfaces with this squirter!",
    "Mist Cloud Release": "FOG MACHINE FEATURE! Spray for smokescreen special effects!",
    "Ink Squirt Defense": "OCTOPUS ESCAPE! Fill with black water for cephalopod camouflage!",
    "Foam Blaster": "BUBBLE BARRAGE! Loads soap solution for foamy firefight!",
    "Chemical Spray": "LAB EXPERIMENT! Mix colors for custom combat cocktails!",
    "Wall-climbing Hands": "SPIDER GRIP! These sucker palms stick to any smooth surface!",
    "Gecko Grip Feet": "CEILING CRAWLER! These pads enable upside-down adventures!",
    "Suction Cup Pads": "VACUUM VICTORY! These attachment points hold tight anywhere!",
    "Spider Web Shooter": "WEB-SLINGING WARRIOR! Sticky string stops enemies in their tracks!",
    "Magnetic Attachment": "METAL MAGNET MASTER! These powered pads attract and hold steel!",
    "Sticky Goo Gun": "GLUE GUN GLORY! This adhesive arsenal immobilizes instantly!",
    "Vacuum Grip": "SUCTION SUCCESS! This powered grip picks up and holds anything!",
    "Velcro Tactical Strips": "RIP-AWAY READY! Attach accessories anywhere with hook-and-loop!",
    "Adhesive Bomb": "STICK-IT SABOTAGE! These putty packages stay where placed!",
    "Gripping Tentacles": "OCTOPUS OPPORTUNITY! These flexible fingers grasp and grab!",
    "Flip-change Head": "DOUBLE IDENTITY! Rotate for battle damage or secret identity!",
    "Weapon Convert Arms": "ARM-AMENT AMAZING! Pop-off hands reveal hidden weapons!",
    "Vehicle Mode Chest": "CAR-CHEST CONVERSION! Open chest to reveal vehicle dashboard!",
    "Battle Damage Reveal": "DAMAGE DISPLAY! Rotate to show wounded warrior status!",
    "Hidden Blade Pop-out": "SURPRISE SWORD! Press to extend secret stabbing action!",
    "Armor Flip Feature": "QUICK-CHANGE COVERING! Flip panels for light or heavy armor!",
    "Face-change Helmet": "MOOD MASK! Rotate for emotion expression variety!",
    "Stealth Mode Shift": "INVISIBLE INSTANTLY! Flip for color-changing camouflage effect!",
    "Power-up Transform": "SUPER MODE SWITCH! Transform to reveal ultimate attack form!",
    "Emergency Mode": "PANIC PROTOCOL! One button transforms to emergency action mode!",
    "Pop-off Arm Cannon": "DETACH AND DESTROY! Remove arm to reveal mega-blaster underneath!",
    "Detach Chest Plate": "CORE EXPOSED! Remove armor to show pulsing power interior!",
    "Remove Helmet Action": "FACE REVEAL! Pop off protective gear to expose face beneath!",
    "Swap Hands/Weapons": "GRIP CHANGE GLORY! Trade peaceful palms for weapons instantly!",
    "Change-out Legs": "LEG SWAP LIBERTY! Boots to wheels to hover jets quickly!",
    "Modular Body Parts": "BUILD-A-BEAST! Mix and match monster parts for endless combos!",
    "Battle Damage Pieces": "WAR WOUNDS! Snap on scars and scratches for battle-worn look!",
    "Weapon Storage Limbs": "ARSENAL APPENDAGES! Hollow limbs hide miniature armory!",
    "Costume Quick Change": "OUTFIT OVERHAUL! Snap on new uniform in seconds!",
    "Accessory Mounts": "GEAR GRAPPLE POINTS! Specially designed sockets hold extras perfectly!",

    // Section 6: Color Schemes descriptions
    "Electric Blue": "LIGHTNING STRIKES AWESOME! This voltage-charged hue crackles with electric energy!",
    "Hot Pink Plasma": "PINK POWER SUPREME! This fluorescent fury burns brighter than enemy dreams!",
    "Laser Red": "BEAM BLAST BRILLIANCE! This target-locking red radiates deadly precision!",
    "Toxic Green": "RADIOACTIVE RADIANCE! This glowing green warns of mutant mayhem within!",
    "Nuclear Yellow": "URANIUM SUNSHINE! This isotope-inspired yellow burns with atomic energy!",
    "Cyber Purple": "DIGITAL DREAM SHADE! This high-tech hue processes combat in nanoseconds!",
    "Radiation Orange": "MELTDOWN MAGNIFICENCE! This warning-color orange signals danger deluxe!",
    "Alien Teal": "EXTRATERRESTRIAL EXCELLENCE! This otherworldly hue defies Earth's color spectrum!",
    "Mutant Magenta": "EVOLUTION ERROR! This genetic glitch color marks the future of fighting!",
    "Plasma White": "PURE ENERGY EMBODIED! This supernova shade outshines the competition!",
    "Highlighter Yellow": "ILLUMINATE AND ANNIHILATE! This construction-site color makes safety and combat shine!",
    "Safety Orange": "CAUTION: EXTREME AWESOMENESS! This high-visibility hue highlights heroism!",
    "Shocking Pink": "RETINA-BURNING RADNESS! This fluorescent fighter demands attention!",
    "Visibility Green": "EMERGENCY EXCELLENCE! This high-viz hero glows with go-time gusto!",
    "Neon Lime": "ZEST FOR JUSTICE! This citrus-powered shade energizes any mission!",
    "UV Reactive Blue": "BLACKLIGHT BATTLE READY! This ultraviolet warrior glows under pressure!",
    "Emergency Red": "ALARM ACTIVATED! This screaming scarlet signals serious action ahead!",
    "Fluorescent Purple": "PRINCE-WORTHY POWER! This royal rebel color rules the night!",
    "Warning Yellow": "HAZARD HIGHLIGHTED! This beacon brightness blinds bad guys!",
    "Blacklight Green": "GLOW PARTY GUARDIAN! This phosphorescent fighter lights up the club!",
    "Chrome Silver": "MIRROR MAYHEM! This reflective warrior blinds enemies with brilliance!",
    "Battle Gold": "TROPHY TAKER! This champion color celebrates countless victories!",
    "Gunmetal Blue": "INDUSTRIAL INTIMIDATION! This steel-storm shade speaks softly, strikes hard!",
    "Bronze Warrior": "ANCIENT METAL, MODERN MUSCLE! This classic color corrodes resistance!",
    "Copper Combat": "CONDUCTIVITY CHAMPION! This penny-colored powerhouse electrifies enemies!",
    "Steel Gray": "FORTRESS FRAMEWORK! This structural shade builds indestructible heroes!",
    "Iron Red": "RUST-PROOF RAGE! This oxidized overlord controls corrosion and combat!",
    "Titanium White": "STRONGEST-METAL STYLING! This spacecraft-grade shade survives anything!",
    "Platinum Blonde": "PRECIOUS METAL PERFECTION! This rare-earth raider rules with luxury!",
    "Mercury Liquid": "QUICKSILVER QUICKNESS! This living-metal finish flows with fatal grace!",
    "Cool to Warm Red": "TEMPERATURE TRACKER! Touch transforms blue calm to red rage!",
    "Ice to Fire Blue": "THERMAL THUNDER! Watch arctic azure ignite to inferno indigo!",
    "Shadow to Light Purple": "MOOD RING MAYHEM! Dark mystery melts to neon nightmare!",
    "Camo to Warning Orange": "STEALTH TO SCREAM! Invisible forest fades to emergency alert!",
    "Stealth Black to Bright Yellow": "MIDNIGHT TO HIGHLIGHT! Shadow transforms to spotlight!",
    "Ocean Blue to Blood Red": "DEEP PEACEFUL TO DEADLY! Waves of vengeance rise from depths!",
    "Forest Green to Toxic Yellow": "NATURE TO NUCLEAR! Peaceful pines poison to power!",
    "Space Black to Nebula Purple": "VOID TO VIBRANT! Dark matter erupts into cosmic color!",
    "Desert Tan to Alert Red": "CAMOUFLAGE TO COMBAT! Sand melts to strike-force scarlet!",
    "Arctic White to Danger Orange": "BLIZZARD TO BLAST! Snowstorm shifts to solar flare!",
    "Phantom Green": "SPECTER GLOW! This ghostly green haunts darkness with deadly light!",
    "Ghostly White": "SPIRIT SHINE! This ethereal essence illuminates the afterlife!",
    "Spectral Blue": "PHANTASM PHOSPHOR! This supernatural shade spectres through shadows!",
    "Radioactive Yellow": "URANIUM UNDERGLOW! This isotope inspiration glows with gamma!",
    "Undead Purple": "RESURRECT RADIANCE! This zombie zone color crawls with dark life!",
    "Spirit Green": "ECT-GLOW! This supernatural shine summons spectral support!",
    "Lunar Silver": "MOONLIGHT MAGIC! This celestial shine guides heroes through darkness!",
    "Eclipse Black": "SOLAR SHADOW! This darkness-within-darkness pulses with negative light!",
    "Cosmic Blue": "STARLIGHT STRIKE! This nebula night-light navigates infinite space!",
    "Supernatural Orange": "MYSTIC FLAME! This otherworldly orange burns beyond normal light!",
    "Mirror Chrome": "REFLECTION PERFECTION! This flawless finish reflects failure!",
    "Brushed Steel": "INDUSTRIAL IMPACT! This textured metal shows scratches of success!",
    "Liquid Silver": "MERCURY METHOD! This flowing finish pools in enemy wounds!",
    "Reflective Platinum": "RARE METAL RANK! This premium patina presents prestige!",
    "Tactical Gray": "STEALTH STEEL! This muted metal masks menace marvelously!",
    "Space Silver": "ASTRONAUT ALUMINUM! This cosmic coating cruises through vacuum!",
    "Battle Chrome": "WAR-TESTED SHINE! This combat coating collects glory!",
    "Tech Steel": "CIRCUIT SILVER! This microchip metal conducts computing coolness!",
    "Cyber Silver": "DIGITAL CHROME! This binary brightness calculates casualties!",
    "Stealth Black": "SHADOW SUPREME! This void-like varnish vanishes villains!",
    "Shadow Gray": "GHOST GRAY! This fog-like finish filters through fortresses!",
    "Tactical Black": "MISSION MIDNIGHT! This operational obsidian operates undetected!",
    "Void Dark": "DEEP SPACE DARKNESS! This cosmic cavity consumes light itself!",
    "Urban Gray": "CITY CAMOUFLAGE! This concrete coating conceals in metropolis!",
    "Night Operation": "MIDNIGHT MISSION READY! This operative onyx obscures objectives!",
    "Obsidian Black": "VOLCANIC VOID! This igneous intensity intimidates instantly!",
    "Charcoal Gray": "ASH AFTERMATH! This smoldering shade shows battle burns!",
    "Midnight Blue-Black": "DARKEST HOUR! This nearly-night nuance navigates shadows!",
    "Carbon Fiber": "HIGH-TECH DARKNESS! This composite coating combines strength and stealth!",
    "Royal Gold": "EMPEROR'S EDGE! This monarch metal marks leadership!",
    "Battle Bronze": "WARRIOR WEALTH! This combat copper celebrates centuries of conflict!",
    "Champion Yellow": "VICTORY VALOR! This prize patina proves supreme!",
    "Commander Brass": "LEADERSHIP LUSTER! This officer's gold outranks opposition!",
    "Elite Gold": "SPECIAL FORCES SHINE! This exclusive excellence elevates elites!",
    "Victory Yellow": "TRIUMPH TINT! This winning wavelength welcomes champions!",
    "Trophy Gold": "AWARD-WINNING ACCENT! This prize-worthy patina presents perfection!",
    "Leader Bronze": "COMMAND COPPER! This authority alloy announces ascendance!",
    "Hero Gold": "LEGENDARY LUSTER! This hall-of-fame hue honors heroes!",
    "Glory Yellow": "ACHIEVEMENT ALLOY! This golden goal glorifies greatness!",
    "Danger Red Stripe": "WARNING BAND! This hazard highlight announces harm!",
    "Warning Yellow Band": "CAUTION COLLAR! This alert accent advises awareness!",
    "Rank Blue Mark": "STATUS STRIPE! This privilege pinstripe positions prestige!",
    "Team Green Badge": "SQUAD SYMBOL! This unit identifier unites allies!",
    "Squad Purple ID": "PLATOON PATCH! This faction flash forms formations!",
    "Unit Orange Flash": "BATTALION BAND! This corps color calls troops together!",
    "Mission Red Patch": "OPERATION ORANGE! This assignment accent activates action!",
    "Faction Blue Symbol": "ALLIANCE AZURE! This loyalty logo links legions!",
    "Special Force Mark": "ELITE EMBLEM! This select stripe shows special status!",
    "Combat Highlight": "BATTLE BADGE! This war wound welcomes warriors!",

     // Section 7: Special Features/Abilities descriptions
    "Fire Blaster": "INFERNO INCARNATE! This pyro-powered warrior ignites injustice with scorching red energy!",
    "Ice Cannon": "ABSOLUTE ZERO AUTHORITY! This cryogenic combatant freezes foes with sub-zero ice blasts!",
    "Lightning Generator": "THUNDERBOLT THROWER! This storm-summoning soldier strikes with yellow electrical devastation!",
    "Wind Vortex": "TORNADO TITAN! This cyclone conjurer creates clear spiraling destruction!",
    "Earth Shaker": "SEISMIC SMASHER! This earthquake initiator launches liquefying brown force!",
    "Water Control": "TIDAL TERROR! This aquatic architect commands oceans with crystal clear power!",
    "Plasma Energy": "IONIZED INTENSITY! This matter-melting master radiates pink plasma perfection!",
    "Laser Power": "PHOTON FURY! This light-speed launcher beams blazing green destruction!",
    "Radiation Field": "TOXIC TREMOR! This isotope instigator emits emerald waves of annihilation!",
    "Shadow Energy": "DARKNESS DEPTHS! This void-void venture channels purple negative energy!",
    "Active Camouflage": "INVISIBILITY ACTIVATED! This hi-tech hide-and-seek hero vanishes in plain sight!",
    "Sound Dampening": "SILENT ASSASSIN! This noise-nullifying ninja moves without making a murmur!",
    "Heat Signature Block": "THERMAL GHOST! This temperature-trickster fools infrared technology!",
    "Motion Sensor Jamming": "MOVEMENT MASKED! This signal-scrambler simulates stationary status!",
    "Optical Illusion": "MIRAGE MASTER! This visual-voodoo specialist creates convincing copies!",
    "Smoke Screen Deploy": "FOG OF WAR! This concealment specialist creates blinding barriers!",
    "Holographic Decoy": "DIGITAL DOUBLE! This projection pro produces perfect replicas!",
    "Scent Masking": "ODORLESS OPERATIVE! This smell-shield specialist blocks tracking dogs!",
    "Electronic Jamming": "SIGNAL STOPPER! This communication-cutter creates transmission chaos!",
    "Light Bending": "REALITY WARPER! This refraction rebel redirects light rays!",
    "Power Lifting": "PLANET-PUSHING POWER! This muscle-bound monarch moves mountains!",
    "Wall Breaker": "BARRIER BUSTER! This architecture-annihilating force punches through buildings!",
    "Tank Thrower": "ARTILLERY ATHLETE! This heavy-hardware hurler tosses tanks like toys!",
    "Building Mover": "SKYSCRAPER SHIFTER! This urban urban-renewal expert relocates real estate!",
    "Ground Pound": "EARTH-SHATTERING EARTHQUAKER! This seismic slammer splits streets!",
    "Seismic Punch": "MAGNITUDE MAKER! This geological jab generates geological mayhem!",
    "Rail Bending": "TRAIN-TRACK TWISTER! This locomotive-line bender reshapes railways!",
    "Vehicle Crusher": "AUTOMOBILE ANNIHILATOR! This car-compacting champion crushes Chrome!",
    "Boulder Toss": "ROCK-THROWING REALITY! This stone-slinging strongman hurls hundred-ton hunks!",
    "Metal Rending": "STEEL SHREDDER! This metallurgic mutilator tears titanium like tissue!",
    "Rocket Boots": "BLAST-OFF BOOTS! These propulsion pumps launch heroes to heavenly heights!",
    "Wing Systems": "AVIAN AUGMENTATION! These mechanical pinions provide powered aerial prowess!",
    "Anti-gravity Pack": "PHYSICS-DEFYING FLIGHT! This gravity-negating gear generates weightless wonder!",
    "Hover Platform": "FLOATING FOOTHOLD! This levitation station lifts lighter than air!",
    "Propulsion Jets": "TURBINE THRUST! These jet-engines juice warriors past supersonic!",
    "Glide System": "CONTROLLED DESCENT! These airfoil additions allow amazing aerial acrobatics!",
    "Telekinetic Lift": "MIND OVER MATTER! This psychic projection provides perfect aerial positioning!",
    "Magnetic Levitation": "POLAR PROPULSION! This attraction-repulsion system suspends subjects scientifically!",
    "Energy Wings": "PLASMA PINIONS! These energy appendages enable ethereal aviation!",
    "Jet Propulsion": "AFTERBURNER ACCELERATION! These thrust tubes push past atmospheric escape velocity!",
    "Deep Sea Pressure Suit": "ABYSS ARMOR! This compression-resistant covering conquers crushing depths!",
    "Oxygen Recycler": "BREATHING BREAKTHROUGH! This gill-mimicking gear generates endless air supply!",
    "Sonar System": "SOUND-SIGHT SCANNER! This echolocation equipment echoes enemy locations!",
    "Torpedo Launcher": "SUBMARINE STRIKE! This underwater arsenal fires fish-shaped fury!",
    "Sub Mode Transform": "VEHICLE VARIATION! This transformation tech turns hero into submarine!",
    "Aquatic Propulsion": "FISH-FAST FINS! These hydro-thrusters push through pressure!",
    "Harpoon System": "SPEAR-GUN SPECIAL! This pronged projectile pierces prey perfectly!",
    "Underwater Vision": "AQUATIC OPTICS! These specialized scopes see through sea-spray!",
    "Diving Bell Mode": "PRESSURE POD! This depth-defying dome delivers safe submarine exploration!",
    "Pressure Cannon": "WATER-WEAPON WONDER! This hydraulic howitzer harnesses H2O power!",
    "Vacuum Suit": "COSMOS COCOON! This stellar shell shields from suffocating space!",
    "Rocket Maneuvering": "ATTITUDE ADJUSTMENT! These thrusters turn warriors weightlessly!",
    "Space Walk Pack": "EXTRAVEHICULAR EXCELLENCE! This tether-terminated system secures space-strolls!",
    "Gravity Generator": "EARTH-NORMAL EMULATOR! This field projector fakes familiar physics!",
    "Oxygen System": "LIFE-SUPPORT LUXURY! This breathing backup ensures endless exploration!",
    "Radiation Shield": "COSMIC RAY PROTECTOR! This force-field filters fatal space particles!",
    "Asteroid Belt Mode": "METEOR MASTERY! This configuration crushes comet collisions!",
    "Solar Powered": "STAR-CHARGED STAMINA! This photovoltaic fighter fuels from fusion!",
    "Space Combat Pack": "ORBITAL ASSAULT ARRAY! This weightless weapons platform packs planet-cracking power!",
    "Zero-G Navigation": "FLOATING FIGHTER! This orientation override enables effortless space-swimming!",
    "Martial Arts Master": "BLACK BELT BRILLIANCE! This fighting form fusion defeats with a thousand styles!",
    "Weapon Expert": "ARMORY AUTHORITY! This arsenal aficionado handles any hardware!",
    "Sharpshooting Precision": "BULLSEYE BRAIN! This targeting talent threads needles at a thousand yards!",
    "Hand-to-Hand Champion": "BARE-KNUCKLE BRAWLER! This pugnacity professional needs no weapons!",
    "Sword Master": "BLADE BALLET! This cutting-edge craftsman carves combat into art!",
    "Archery Specialist": "ARROW ARTIST! This bow-bending bowman bullseyes from impossible angles!",
    "Explosive Expert": "DEMOLITION DYNAMO! This blast specialist calculates controlled chaos!",
    "Vehicle Commander": "TRANSPORT TACTICIAN! This pilot prodigy operates any war machine!",
    "Squad Tactics": "TEAM TERMINATOR! This formation genius commands cooperative carnage!",
    "Siege Breaker": "FORTRESS FUTILITY! This wall-walker makes mockery of defenses!",

    // Section 8: Faction/Team Alignment descriptions
    "Patriot Blue Squadron": "FREEDOM FIGHTERS ASSEMBLE! These star-spangled soldiers stand for liberty and laser-blasts!",
    "Freedom Red Force": "LIBERTY'S LEGION! These crimson commandos cut through oppression with righteous rage!",
    "Liberty White Unit": "PURE-HEARTED PROTECTORS! These unstained warriors shine with justice and valor!",
    "Justice Rangers": "LAW-ENFORCEMENT ELITE! These badge-bearing warriors bring balance to chaos!",
    "Allied Command": "UNITED NATIONS OF AWESOME! This international alliance obliterates evil everywhere!",
    "International Defense": "GLOBAL GUARDIAN FORCE! These worldwide warriors defend democracy deluxe!",
    "Global Security Task Force": "PLANET-WIDE PROTECTORS! This security squadron safeguards civilization!",
    "United Assault Team": "COALITION OF COMBAT! These combined forces create unstoppable offense!",
    "Peace Keeper Corps": "HARMONY HEAVYWEIGHT! These tranquility troopers terminate threats permanently!",
    "World Guardian Alliance": "EARTH'S ELITE DEFENDERS! This planetary protection force prevents apocalypse!",
    "Dark Legion Black": "SHADOW SOLDIERS SUPREME! These ebony enforcers enforce evil empire's orders!",
    "Doom Brigade Red": "CRIMSON CONQUERORS! These scarlet scoundrels spread destruction delightfully!",
    "Chaos Command Purple": "ANARCHY ARMY! These violet villains create calculated confusion!",
    "Evil Empire Green": "EMERALD EMPIRE! These jade jeopardizers hunger for world domination!",
    "Shadow Force Gray": "GHOST GUARD! These smoky soldiers serve shadowy schemes!",
    "Destruction Army Yellow": "GOLDEN GOON SQUAD! These banana-bright baddies blast beautiful things!",
    "Terror Battalion Orange": "PUMPKIN PLATOON! These terror-inducing troops terrorize totally!",
    "Hate Squad Pink": "COTTON-CANDY CARNAGE! These pastel predators prove evil comes in pretty packages!",
    "Corrupt Regime Silver": "METALLIC MENACE! These chrome criminals chase profit over people!",
    "Malice Division Gold": "TWENTY-FOUR KARAT KILLERS! These precious-metal psychos pursue pain!",
    "Freelance Force": "CASH-FOR-COMBAT! These profit-motivated professionals practice paycheck warfare!",
    "Contract Warriors": "HIRED GUNS OF JUSTICE! These signature soldiers sell their skills to highest bidders!",
    "Independent Unit": "NEITHER GOOD NOR EVIL! These solo specialists serve themselves spectacularly!",
    "Bounty Hunter Guild": "DEAD OR ALIVE DELIVERY! These price-tagged pursuers possess portable prisons!",
    "Mercenary Exchange": "FREELANCER MARKETPLACE! These soldier-for-sale specialists swap sides for silver!",
    "Professional Soldiers": "BUSINESS AS USUAL! These combat contractors conduct war like corporate meetings!",
    "For-Hire Squad": "TEMPORARY TEAM! These rental rangers rent remarkable results!",
    "Private Defense Force": "SECURITY SOLUTIONS! These protective professionals guard for gold!",
    "Neutral Zone Patrol": "MIDDLE-GROUND MILITIA! These impartial intermediaries intervene in conflicts!",
    "Rogue Operations": "OFF-THE-BOOKS BRIGADE! These unsanctioned units undertake unauthorized adventures!",
    "Delta Force Elite": "TOP SECRET TERMINATORS! These classified commandos crack impossible missions!",
    "Special Operations Black": "COVERT COMBAT! These shadow specialists splice silence with sudden violence!",
    "SEAL Team Advanced": "AQUATIC ASSAULT ACES! These amphibious athletes annihilate anywhere!",
    "Royal Guard Unit": "CROWN'S CHAMPIONS! These palace protectors preserve royal bloodlines!",
    "Presidential Guard": "COMMANDER-IN-CHIEF COVERAGE! These executive escorts ensure survival!",
    "Top Secret Division": "CLASSIFIED COLLECTION! These redacted raiders redefine ruthless!",
    "Classified Operations": "EYES-ONLY ENFORCERS! These sensitive specialists secure secrets!",
    "Strike Force One": "FIRST-RESPONSE FURY! These rapid-reaction raiders reach trouble instantly!",
    "Ghost Patrol": "INVISIBLE INFANTRY! These phantom fighters fade but never fail!",
    "Covert Action Team": "QUIET PROFESSIONALS! These silent servicemen serve without recognition!",
    "Galactic Empire": "STAR-SPANNING SOVEREIGNTY! These cosmic conquerors claim countless civilizations!",
    "Star Federation": "UNITED UNIVERSE! These interstellar allies assemble for astronomical adventures!",
    "Cosmic Alliance": "FEDERATION OF FUTURES! These space-bound species share scientific supremacy!",
    "Interstellar Union": "PLANETARY PARTNERSHIP! These celestial citizens cooperate cosmically!",
    "Planet Defense Council": "WORLD-WATCH WARRIORS! These orbital overlords orchestrate protection protocols!",
    "Space Colonist Force": "FRONTIER FIGHTERS! These settler soldiers secure new solar systems!",
    "Alien Hunter Corps": "XENOMORPH EXTERMINATORS! These space-species specialists seek strange specimens!",
    "Celestial Warriors": "HEAVENLY HOST! These divine defenders descend from distant dimensions!",
    "Universal Protectors": "REALITY RANGERS! These multiversal marshals maintain cosmic order!",
    "Orbital Command": "SATELLITE SOVEREIGNTY! These space-station strategists supervise stellar security!",
    "Creature Patrol": "BEAST BRIGADE! These monstrous marvels march for mayhem!",
    "Beast Legion": "WILDLIFE WARRIORS! These animalistic aberrations attack aggressively!",
    "Monster Menace": "FREAK FORCE! These nightmare nightmare navigators terrorize townships!",
    "Mutant Brigade": "GENETIC GLADIATORS! These DNA-damaged destroyers devastate delightfully!",
    "Horror Squad": "FEAR FACTOR FORCE! These terror-inducing troops traumatize thoroughly!",
    "Freak Force": "SIDESHOW SOLDIERS! These carnival crazies create chaos comically!",
    "Undead Army": "RISEN REGIMENT! These resurrection raiders return for revenge!",
    "Abomination Unit": "SCIENTIFIC SINS! These laboratory lambdas leak into reality!",
    "Nightmare Division": "DREAM DESTROYERS! These sleep-stalking soldiers spawn in subconscious!",
    "Creature Commandos": "MONSTER MILITARY! These beastly berserkers blend brutality with brotherhood!",

    // Section 9: Costume Elements descriptions
    "Shoulder Pauldrons Only": "GLADIATOR GUARDS! These bulked-up body panels project prestige and protection!",
    "Chest Plate & Gauntlets": "VITAL VITALS PROTECTED! This heart-shield and hand-guards combo commands combat!",
    "Full Body Plate": "WALKING TANK! This head-to-toe steel shell transforms warrior into mobile fortress!",
    "Half Armor Left Side": "ASYMMETRIC ADVANTAGE! This partial plating provides protection while preserving mobility!",
    "Modular Tech Armor": "MIX-AND-MATCH METAL! These snap-lock segments scale protection to mission!",
    "Battle Damage Armor": "SCARRED STRENGTH! This pre-worn plating proves proven protection!",
    "Light Recon Armor": "STEALTH SHELL! This minimal metal maximizes movement while maintaining defense!",
    "Heavy Assault Plate": "MAXIMUM PROTECTION! This overlapping armor laughs at laser-blasts and shrapnel!",
    "Tactical Vest System": "QUICK-DEPLOY COVERAGE! This modular defense adapts to any assault scenario!",
    "Knight-style Full Suit": "MEDIEVAL MEETS MODERN! This jointed metal suit jousts with justice!",
    "Military One-Piece": "REGULATION READY! This camo-classic covers combat from collar to combat boots!",
    "Space EVA Suit": "VACUUM VALIDATED! This pressurized protection proves perfect for deep space!",
    "Ninja Stealth Gear": "SHADOW SUIT! This matte-black bodysuit absorbs light and attention!",
    "Hazmat Containment": "BIOHAZARD BLOCKADE! This sealed suit stops spills and spreads alike!",
    "Riot Control Outfit": "CROWD CONTROL COSTUME! This certified protection handles hostile masses!",
    "Desert Combat Gear": "SAND SPECIALIST SUIT! This thermal-regulated gear tackles desert duty!",
    "Arctic Survival Suit": "SUB-ZERO SURVIVOR! This insulated ensemble endures endless ice!",
    "Urban Warfare Uniform": "CONCRETE COMBAT! This city-adapted attire maneuvers metropolitan mayhem!",
    "Jungle Camouflage": "FOREST FADE! This photosynthetic pattern blends perfectly into thick vegetation!",
    "Deep Space Exploration": "VOID VOYAGER! This cosmic coverall conquers infinite dark!",
    "Lightning Bolt Chest": "SPEED SYMBOL! This jagged emblem announces electrical excellence!",
    "Skull and Crossbones": "PIRATE PRIDE! This classic symbol signals dangerous waters ahead!",
    "Star Command Badge": "GALACTIC GLORY! This celestial symbol represents stellar standing!",
    "Dragon Symbol Patch": "REPTILIAN RESPECT! This mythic marker manifests monstrous might!",
    "Team Number Decal": "NUMERICAL NOTATION! This jersey-style identifier indexes individual identity!",
    "Rank Insignia": "PROMOTION PATCHES! These status symbols separate soldiers by service!",
    "Squad Logo Shield": "UNIT UNITY! This emblazoned escutcheon builds brotherhood in battle!",
    "Operation Name Tag": "MISSION MARKER! This textual tag tracks tactical assignments!",
    "Unit Motto Banner": "INSPIRATIONAL INSCRIPTION! This rallying ribbon records regimental creed!",
    "Battle Honor Ribbon": "VICTORY VERIFICATION! This colored strip certifies combat achievements!",
    "Ammo Bandolier": "BULLET BALLET! This crossed cartridge carrier creates bullet ballerina!",
    "Utility Belt System": "GADGET GRID! This compartment constellation contains convenient contraptions!",
    "Tactical Thigh Straps": "LEG-LOADED LOGISTIC! These supplemental straps supply secondary supplies!",
    "Equipment Harness": "GEAR GRID! This webbing wonder distributes weight wonderfully!",
    "Weapon Carry Belt": "ARSENAL ACCESSIBILITY! This quick-draw system delivers deadly devices!",
    "Tool Loop Belt": "MECHANIC'S MARVEL! This instrument holder keeps kits conveniently close!",
    "Grenade Belt": "EXPLOSIVE ENSEMBLE! This boom-bearing belt delivers devastating devices!",
    "Communication Pack Belt": "RADIO READY! This transmission strap streamlines signal sending!",
    "Power Cell Belt": "ENERGY ENSEMBLE! This battery band provides portable power packs!",
    "Survival Gear Strap": "EMERGENCY EQUIPMENT! This life-saving strap secures survival supplies!",
    "Combat Infantry Boots": "BATTLEFIELD TREADERS! These reinforced stompers crush terrain and tension!",
    "Rocket Thrust Boots": "BOOT-SCOOTER BLAST! These propelled pumps provide portable propulsion!",
    "Magnetic Grip Soles": "WALL-WALKER WONDERS! These attraction-action boots beat gravity!",
    "Spring-loaded Boots": "SUPER-JUMP STARTS! These elastic enhancements enable enormous leaps!",
    "All-terrain Stompers": "MULTI-SURFACE MASTERS! These adaptable ankle-guards handle any environment!",
    "Hover Foot Pads": "FLOATING FOOTWEAR! These antigrav units allow airborne advancement!",
    "Defensive Kick Boots": "FOOT-FIGHTER SPECIAL! These reinforced toe-tips deliver devastating kicks!",
    "Stealth Soft Soles": "SILENT STEP! These padded pumps produce zero noise!",
    "Desert Sand Boots": "DUNE DANCER! These sand-specific shoes shuffle through shifting surfaces!",
    "Deep Space EVA Boots": "VOID VACUUMS! These magnetic moon-boots magnetize to metal!",

    // Section 10: Character Name Generator Components descriptions
    "Commander": "BATTLEFIELD BOSS! This tactical title leads legions to legendary victories through masterful military management!",
    "Captain": "COMPANY CHIEF! This resolute rank rallies troops with confidence earned through countless combat campaigns!",
    "Major": "BATTALION BRIGADIER! This strategic specialist coordinates complex operations while commanding considerable respect!",
    "General": "WAR WIZARD! This supreme strategist shapes battlefields through brilliant planning and fearless leadership execution!",
    "Sergeant": "SQUAD SHEPHERD! This gritty ground-leader guides green recruits while maintaining mission-critical momentum menacingly!",
    "Colonel": "REGIMENT RULER! This iron-fisted individual orchestrates overwhelming offense through organizational excellence!",
    "Marshal": "MILITARY MONARCH! This decorated dynamo possesses absolute authority over armed forces and strategic decisions!",
    "Lieutenant": "JUNIOR JUGGERNAUT! This rising rank bridges command structure while proving potential through battlefield brilliance!",
    "Chief": "SENIOR SOVEREIGN! This veteran voice commands respect while coordinating critical operations across combat zones!",
    "Master": "PEAK PROFESSIONAL! This martial maestro perfects combat arts while pursuing excellence in every engagement!",
    "Laser": "LIGHT-SPEED LIQUIDATOR! This photonic powerhouse channels concentrated radiation into reality-ripping rays!",
    "Turbo": "TURBOCHARGED TERROR! This supercharged speed demon accelerates action to astronomical levels instantly!",
    "Ultra": "EXTREME EXCELLENCE! This maximum modifier magnifies might to undreamed-of ultrasonic ultimates!",
    "Mega": "MASSIVE MAGNITUDE! This power multiplier pumps performance to planetary proportions powerfully!",
    "Super": "SUPERNATURAL SUPREMACY! This classic enhancer cranks capabilities beyond conventional comprehension!",
    "Hyper": "HEIGHTENED HAVOC! This intensity intensifier inflates impact to incomprehensible increments!",
    "Power": "RAW POTENTIAL! This fundamental force fuels feats of fantastic physics-defying proportions!",
    "Force": "FUNDAMENTAL FURY! This elemental energy emerges as unstoppable offensive operations!",
    "Blast": "EXPLOSIVE ENGAGEMENT! This high-powered technique releases energy in concentrated catastrophic bursts!",
    "Storm": "TEMPEST TERROR! This meteorological mayhem manifests as maelstroms of magnificent martial might!",
    "Strike": "PRECISION PUNISHMENT! This targeted termination technique delivers devastation with laser-like accuracy!",
    "Slash": "RAZOR RAGE! This cutting-edge combat move carves catastrophe through enemy formations!",
    "Crush": "OVERWHELMING OBLITERATION! This crushing combat technique compresses opposition into oblivion!",
    "Smash": "BRUTAL BREAKTHROUGH! This devastating destruction technique demolishes defenses definitively!",
    "Charge": "MOMENTUM MASSACRE! This forward-focused assault overwhelms opposition through overwhelming offense!",
    "Attack": "OFFENSIVE ONSLAUGHT! This aggressive approach annihilates adversaries through relentless reality!",
    "Assault": "FULL-SCALE FURY! This comprehensive combat technique coordinates multiple maneuvers magnificently!",
    "Impact": "COLLISION CONCLUSION! This crash-course combat method maximizes mass and momentum magnificently!",
    "Surge": "POWER PULSE! This energy-enhanced engagement supercharges strikes with supplemental strength!",
    "Hawk": "SKY SENTINEL! This aerial assassin swoops silently through clouds while hunting with hyper-vision!",
    "Snake": "SLITHERING STRIKER! This scale-covered saboteur strikes with venomous velocity and predatory precision!",
    "Tiger": "STRIPED STALKER! This jungle juggernaut pounces with premeditated power and feline ferocity!",
    "Wolf": "PACK PREDATOR! This lunar legend leads lupine legions while howling haunting harmonies!",
    "Dragon": "MYTHIC MONSTER! This fire-breathing force combines reptilian rage with legendary destruction!",
    "Shark": "OCEAN ANNIHILATOR! This finned fury patrols waters while terrorizing with tooth-filled terror!",
    "Eagle": "PATRIOTIC PREDATOR! This crowned carnivore commands aerial assault with talon-tipped tenacity!",
    "Tank": "ARMORED ANNIHILATOR! This tracked terror thunders through terrain while delivering devastating payloads!",
    "Blade": "EDGED ELIMINATOR! This sharpened slasher cuts through carbon and controversy alike!",
    "Laser": "LIGHT LIQUIDATOR! This focused photon beam burns through barriers with blinding brilliance!",
    "Ice": "FROZEN FURY! This arctic assault channels crystalline cold into devastating defensive displays!",
    "Fire": "INFERNO INCARNATE! This blazing berserker burns bright while bringing blistering destruction!",
    "Storm": "METEOROLOGICAL MAYHEM! This tempest terror summons supernatural weather warfare!",
    "Solar": "STAR-POWERED STRENGTH! This celestial soldier channels infinite cosmic energy!",
    "Lunar": "MOONLIGHT MAGIC! This nighttime navigator harnesses tidal forces for tremendous impact!",
    "Desert": "SAND-STORM SOVEREIGN! This dune domain defender commands scorching endless wastelands!",
    "Arctic": "POLAR POWERHOUSE! This tundra titan navigates negative temperatures with frost-forged fury!",
    "Jungle": "FOREST FURY! This vine-covered victor swings through canopies while commanding natural chaos!",
    "Space": "COSMIC CHAMPION! This stellar sovereign explores galaxies while battling beyond boundaries!",
    "Deep": "ABYSS AUTHORITY! This trench-dwelling terror plunges below pressure while crushing depths!"
};







